# Generated by Django 5.0.2 on 2024-02-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='usr_first_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='usr_last_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
